services:
    postgres:
        image: "postgres:17.4"
        container_name: postgres
        restart: always
        environment:
            - "POSTGRES_DB=library_management"
            - "POSTGRES_PASSWORD=1"
            - "POSTGRES_USER=postgres"
        ports:
            - "5432:5432"
        volumes:
            - ./postgres:/var/lib/postgresql/data

    redis:
        image: "redis:7.2.0"
        container_name: redis
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - ./redis:/data

    # spring-app:
    #   build: .
    #   container_name: spring_server
    #   depends_on:
    #     - postgres
    #   environment:
    #     SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/btl
    #     SPRING_DATASOURCE_USERNAME: postgres
    #     SPRING_DATASOURCE_PASSWORD: 1
    #     SPRING_JPA_HIBERNATE_DDL_AUTO: update
    #     SPRING_DEVTOOLS_RESTART_ENABLED: true
    #   ports:
    #     - "8080:8080"
    #   volumes:
    #     - .:/app

volumes:
    postgres_data:
    redis_data:
        driver: local
